//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accpagibigph3srv.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime SYS_DATE {
            get {
                return ((global::System.DateTime)(this["SYS_DATE"]));
            }
            set {
                this["SYS_DATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CONSO_CNTR {
            get {
                return ((int)(this["CONSO_CNTR"]));
            }
            set {
                this["CONSO_CNTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CONSO_RECARD_CNTR {
            get {
                return ((int)(this["CONSO_RECARD_CNTR"]));
            }
            set {
                this["CONSO_RECARD_CNTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p@gIb1gUbp@CC2019")]
        public string AESKey {
            get {
                return ((string)(this["AESKey"]));
            }
            set {
                this["AESKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=10.88.77.68;Database=LCDB_01;User=allcard;Password=MalboroLights#;")]
        public string DbaseConStr {
            get {
                return ((string)(this["DbaseConStr"]));
            }
            set {
                this["DbaseConStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CONSOFC_CNTR {
            get {
                return ((int)(this["CONSOFC_CNTR"]));
            }
            set {
                this["CONSOFC_CNTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CONSOFC_RECARD_CNTR {
            get {
                return ((int)(this["CONSOFC_RECARD_CNTR"]));
            }
            set {
                this["CONSOFC_RECARD_CNTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=10.88.87.68;Database=LCDB_01_SYS;User=allcard;Password=MikasaAckerman#;")]
        public string CentralDbaseConStr {
            get {
                return ((string)(this["CentralDbaseConStr"]));
            }
            set {
                this["CentralDbaseConStr"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1650/ACC_MS_WEBSERVICE.asmx")]
        public string accpagibigph3srvZIP_bank_ws_ACC_MS_WEBSERVICE {
            get {
                return ((string)(this["accpagibigph3srvZIP_bank_ws_ACC_MS_WEBSERVICE"]));
            }
        }
    }
}
